"use client";

import { useInfiniteQuery, useQuery } from "@tanstack/react-query";
import {
  useProfilesControllerGetMe,
  useProfilesControllerGetLeaderboard,
  useProfilesControllerCreate,
  useProfilesControllerUpdate,
} from "@/api/generated/profiles/profiles";
import type { CreateProfileDto } from "@/api/generated/model/createProfileDto";
import type { UpdateProfileDto } from "@/api/generated/model/updateProfileDto";
import {
  usePriceReportsControllerFindMyReports,
  usePriceReportsControllerFindByUser,
  priceReportsControllerFindMyReports,
  priceReportsControllerFindByUser,
} from "@/api/generated/price-reports/price-reports";
import {
  useScamAlertsControllerFindMyAlerts,
  useScamAlertsControllerFindByUser,
  scamAlertsControllerFindMyAlerts,
  scamAlertsControllerFindByUser,
} from "@/api/generated/scam-alerts/scam-alerts";
import {
  useCommunityTipsControllerFindMyTips,
  useCommunityTipsControllerFindByUser,
  communityTipsControllerFindMyTips,
  communityTipsControllerFindByUser,
} from "@/api/generated/community-tips/community-tips";
import {
  useSpotsControllerFindMySpots,
  useSpotsControllerFindByUser,
  spotsControllerFindMySpots,
  spotsControllerFindByUser,
} from "@/api/generated/spots/spots";
import { getNextSkipFromPage } from "./base";

export function useMyProfile() {
  const query = useProfilesControllerGetMe({ query: { retry: false } });
  return { ...query, data: query.data?.data };
}

export function useLeaderboard(take = 5) {
  const params = { take: String(take) };
  const query = useProfilesControllerGetLeaderboard(params, {
    query: { staleTime: 5 * 60 * 1000 },
  });
  return { ...query, data: query.data?.data };
}

// Note: useProfile(id) was removed as useProfilesControllerFindOne was not generated by Orval
// The API only provides useProfilesControllerGetMe for the current authenticated user
// To view other user profiles, use the user-specific hooks (useInfiniteUserSpots, useInfiniteUserCommunityTips, etc.)

export function useProfile(id: string) {
  return useQuery({
    queryKey: ["profile", id],
    queryFn: async () => {
      const error = new Error("Profile endpoint not available");
      (error as any).response = { status: 404 };
      throw error;
    },
    enabled: !!id && id !== "me",
    retry: false,
  });
}

export function useCreateProfile() {
  const mutation = useProfilesControllerCreate();
  return {
    ...mutation,
    mutate: (data: CreateProfileDto) => mutation.mutate({ data }),
    mutateAsync: (data: CreateProfileDto) => mutation.mutateAsync({ data }),
  };
}

export function useUpdateProfile() {
  const mutation = useProfilesControllerUpdate();
  return {
    ...mutation,
    mutate: (data: UpdateProfileDto) => mutation.mutate({ data }),
    mutateAsync: (data: UpdateProfileDto) => mutation.mutateAsync({ data }),
  };
}

export function useInfiniteUserPriceReports(userId: string) {
  const isMe = userId === "me";
  const myReports = useInfiniteQuery({
    queryKey: ["user-price-reports-infinite", "me"],
    queryFn: async ({ pageParam = 0 }) => {
      const skip = pageParam > 0 ? pageParam : undefined;
      return priceReportsControllerFindMyReports({ take: 10, skip });
    },
    getNextPageParam: (lastPage: unknown) => getNextSkipFromPage(lastPage),
    enabled: isMe,
    initialPageParam: 0,
  });
  const userReports = useInfiniteQuery({
    queryKey: ["user-price-reports-infinite", userId],
    queryFn: async ({ pageParam = 0 }) => {
      const skip = pageParam > 0 ? pageParam : undefined;
      return priceReportsControllerFindByUser(userId, { take: 10, skip });
    },
    getNextPageParam: (lastPage: unknown) => getNextSkipFromPage(lastPage),
    enabled: !isMe && !!userId,
    initialPageParam: 0,
  });
  return isMe ? myReports : userReports;
}

export function useInfiniteUserScamAlerts(userId: string) {
  const isMe = userId === "me";
  const myAlerts = useInfiniteQuery({
    queryKey: ["user-scam-alerts-infinite", "me"],
    queryFn: async ({ pageParam = 0 }) => {
      const skip = pageParam > 0 ? pageParam : undefined;
      return scamAlertsControllerFindMyAlerts({ take: 10, skip });
    },
    getNextPageParam: (lastPage: unknown) => getNextSkipFromPage(lastPage),
    enabled: isMe,
    initialPageParam: 0,
  });
  const userAlerts = useInfiniteQuery({
    queryKey: ["user-scam-alerts-infinite", userId],
    queryFn: async ({ pageParam = 0 }) => {
      const skip = pageParam > 0 ? pageParam : undefined;
      return scamAlertsControllerFindByUser(userId, { take: 10, skip });
    },
    getNextPageParam: (lastPage: unknown) => getNextSkipFromPage(lastPage),
    enabled: !isMe && !!userId,
    initialPageParam: 0,
  });
  return isMe ? myAlerts : userAlerts;
}

export function useInfiniteUserCommunityTips(userId: string) {
  const isMe = userId === "me";
  const myTips = useInfiniteQuery({
    queryKey: ["user-community-tips-infinite", "me"],
    queryFn: async ({ pageParam = 0 }) => {
      const skip = pageParam > 0 ? pageParam : undefined;
      return communityTipsControllerFindMyTips({ take: 10, skip });
    },
    getNextPageParam: (lastPage: unknown) => getNextSkipFromPage(lastPage),
    enabled: isMe,
    initialPageParam: 0,
  });
  const userTips = useInfiniteQuery({
    queryKey: ["user-community-tips-infinite", userId],
    queryFn: async ({ pageParam = 0 }) => {
      const skip = pageParam > 0 ? pageParam : undefined;
      return communityTipsControllerFindByUser(userId, { take: 10, skip });
    },
    getNextPageParam: (lastPage: unknown) => getNextSkipFromPage(lastPage),
    enabled: !isMe && !!userId,
    initialPageParam: 0,
  });
  return isMe ? myTips : userTips;
}

export function useInfiniteUserSpots(userId: string) {
  const isMe = userId === "me";
  const mySpots = useInfiniteQuery({
    queryKey: ["user-spots-infinite", "me"],
    queryFn: async ({ pageParam = 0 }) => {
      const skip = pageParam > 0 ? pageParam : undefined;
      return spotsControllerFindMySpots({ take: 10, skip });
    },
    getNextPageParam: (lastPage: unknown) => getNextSkipFromPage(lastPage),
    enabled: isMe,
    initialPageParam: 0,
  });
  const userSpots = useInfiniteQuery({
    queryKey: ["user-spots-infinite", userId],
    queryFn: async ({ pageParam = 0 }) => {
      const skip = pageParam > 0 ? pageParam : undefined;
      return spotsControllerFindByUser(userId, { take: 10, skip });
    },
    getNextPageParam: (lastPage: unknown) => getNextSkipFromPage(lastPage),
    enabled: !isMe && !!userId,
    initialPageParam: 0,
  });
  return isMe ? mySpots : userSpots;
}
